name: Create New Branch

on:
  create:
    branches:
      - '*'

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create new branch
      run: |
        NEW_BRANCH="new-branch-for-${GITHUB_REF#refs/heads/}"
        git checkout -b $NEW_BRANCH
        git push origin $NEW_BRANCH
