name: Check Dependencies

on:
  schedule:
    - cron: '0 0 * * *'  # Uruchamia co 24 godziny

jobs:
  check_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Wersja Node.js

      - name: Install npm dependencies
        run: npm install

      - name: Check for updates
        run: npm outdated

      - name: Check for security vulnerabilities
        run: npm audit

      - name: Send Slack notification (optional)
        if: success()  # Opcjonalne: Wysyłanie powiadomienia tylko w przypadku braku błędów
        uses: rtCamp/action-slack-notify@v3
        with:
          status: ${{ job.status }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: 'Wymagana aktualizacja zależności w projekcie.'
